version: '3'

services:
  db:
    restart: always
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
  website:
    build: ./website
    container_name: website
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./website:/website
    ports:
      - "8000:8000"
    depends_on:
      - db