version: '3'

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
  website:
    container_name: website
    build: ./website
    command: bash -c "python util.py wait 10 && python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:80"
    volumes:
      - ./website:/website
    ports:
      - "8000:80"
    depends_on:
      - db